apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: mysql
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/uracle/Develop/study/k8s/pv